version: "3"
services: 
    # Nombre de mi imagen que voy a crear.
    dbPostgres:
        # La imagen que voy a usar.
        image: postgres:latest
        # Puerto que escucha la base de datos.
        # env_file: .env
        ports: 
            - 5432:5432
    backend:
        build: ./back
        ports: 
            - "3000:3000"
        volumes: 
            - ./back/routes:/app/routes
            - ./back/models:/app/models
            - ./back/config:/app/config
        depends_on: 
            - dbPostgres
    frontend: 
        build: ./front
        volumes: 
            - ./front/:/app/front/src
