version: "3"
services: 
    # Nombre de mi imagen que voy a crear.
    dbMongo:
        # La imagen que voy a usar.
        image: mongo:latest
        # Puerto que escucha la base de datos.
        ports: 
            - "27017:27017"
    backend:
        build: ./back
        ports: 
            - "3000:3000"
        volumes: 
            - ./back/routes:/app/routes
            - ./back/models:/app/models
            - ./back/config:/app/config
        depends_on: 
            - dbMongo
        environment:
            PORT: "3000" 
            DBURL: "mongodb://localhost:27017/ToDo_ListMongo"
    frontend: 
        build: ./front
